IPA = {
    'ሀ': 'ha',
    'ሁ': 'hu',
    'ሂ': 'hi',
    'ሃ': 'ha',
    'ሄ': 'he',
    'ህ': 'hɨ',
    'ሆ': 'ho',
    'ሇ': 'ho',  # Dizi, Me’en, Mursi, Suri /hɔ/; not used in Amharic.
    'ለ': 'lə',
    'ሉ': 'lu',
    'ሊ': 'li',
    'ላ': 'la',
    'ሌ': 'le',
    'ል': 'lɨ',
    'ሎ': 'lo',
    'ⶀ': 'lo',  # Dizi, Me’en, Mursi, Suri /lɔ/; not used in Amharic.
    'ሏ': 'lwa',
    'ሐ': 'ha',
    'ሑ': 'hu',
    'ሒ': 'hi',
    'ሓ': 'ha',
    'ሔ': 'he',
    'ሕ': 'hɨ',
    'ሖ': 'ho',
    'ሗ': 'hwa',
    'መ': 'mə',
    'ሙ': 'mu',
    'ሚ': 'mi',
    'ማ': 'ma',
    'ሜ': 'me',
    'ም': 'mɨ',
    'ሞ': 'mo',
    'ⶁ': 'mo',  # Dizi, Me’en, Mursi, Suri /mɔ/; not used in Amharic.
    'ᎀ': 'mwə',  # Sebatbeit /mwə/; not used in Amharic.
    'ᎃ': 'mwu',  # Sebatbeit /mwu/; not used in Amharic.
    'ᎁ': 'mwi',  # Sebatbeit /mwi/; not used in Amharic.
    'ሟ': 'mwa',
    'ᎂ': 'mwe',  # Sebatbeit /mwe/; not used in Amharic.
    'ፙ': 'mja',  # Unclear which language; transcribed as /mʲa/.
    'ሠ': 'sə',
    'ሡ': 'su',
    'ሢ': 'si',
    'ሣ': 'sa',
    'ሤ': 'se',
    'ሥ': 'sɨ',
    'ሦ': 'so',
    'ሧ': 'swa',
    'ረ': 'rə',
    'ሩ': 'ru',
    'ሪ': 'ri',
    'ራ': 'ra',
    'ሬ': 're',
    'ር': 'rɨ',
    'ሮ': 'ro',
    'ⶂ': 'ro',  # Dizi, Me’en, Mursi, Suri /rɔ/; not used in Amharic.
    'ሯ': 'rwa',
    'ፘ': 'rja',  # Unclear which language; transcribed as /rʲa/.
    'ሰ': 'sə',
    'ሱ': 'su',
    'ሲ': 'si',
    'ሳ': 'sa',
    'ሴ': 'se',
    'ስ': 'sɨ',
    'ሶ': 'so',
    'ⶃ': 'so',  # Dizi, Me’en, Mursi, Suri /sɔ/; not used in Amharic.
    'ሷ': 'swa',
    'ሸ': 'ʃə',
    'ሹ': 'ʃu',
    'ሺ': 'ʃi',
    'ሻ': 'ʃa',
    'ሼ': 'ʃe',
    'ሽ': 'ʃɨ',
    'ሾ': 'ʃo',
    'ⶄ': 'ʃo',  # Dizi, Me’en, Mursi, Suri /ʃɔ/; not used in Amharic.
    'ሿ': 'ʃwa',
    'ⶠ': 'ʃə',
    'ⶡ': 'ʃu',
    'ⶢ': 'ʃi',
    'ⶣ': 'ʃa',
    'ⶤ': 'ʃe',
    'ⶥ': 'ʃɨ',
    'ⶦ': 'ʃo',
    'ቀ': 'kʼə',
    'ቁ': 'kʼu',
    'ቂ': 'kʼi',
    'ቃ': 'kʼa',
    'ቄ': 'kʼe',
    'ቅ': 'kʼɨ',
    'ቆ': 'kʼo',
    'ቇ': 'kʼo',  # Dizi, Me’en, Mursi, Suri /kʼɔ/; not used in Amharic.
    'ቈ': 'kʼwə',
    'ቍ': 'kʼwu',
    'ቊ': 'kʼwi',
    'ቋ': 'kʼwa',
    'ቌ': 'kʼwe',


    'ቐ': 'kʼə',
    'ቑ': 'kʼu',
    'ቒ': 'kʼi',
    'ቓ': 'kʼa',
    'ቔ': 'kʼe',
    'ቕ': 'kʼɨ',
    'ቖ': 'kʼo',
    'ቘ': 'kʼwə',
    'ቝ': 'kʼwu',
    'ቚ': 'kʼwi',
    'ቛ': 'kʼwa',
    'ቜ': 'kʼwe',
    'ⷀ': 'kʼjə',  # Sebatbeit /kʼʲ/; not used in Amharic.
    'ⷁ': 'kʼju',
    'ⷂ': 'kʼji',
    'ⷃ': 'kʼja',
    'ⷄ': 'kʼje',
    'ⷅ': 'kʼjɨ',
    'ⷆ': 'kʼjo',
    'በ': 'bə',
    'ቡ': 'bu',
    'ቢ': 'bi',
    'ባ': 'ba',
    'ቤ': 'be',
    'ብ': 'bɨ',
    'ቦ': 'bo',
    'ⶅ': 'bo',  # Dizi, Me’en, Mursi, Suri /bɔ/; not used in Amharic.
    'ᎄ': 'bwə',  # Sebatbeit /bʷə/; not used in Amharic.
    'ᎇ': 'bwu',  # Sebatbeit /bʷu/; not used in Amharic.
    'ᎅ': 'bwi',  # Sebatbeit /bʷi/; not used in Amharic.
    'ቧ': 'bwa',  # Sebatbeit /bʷa/; not used in Amharic.
    'ᎆ': 'bwe',  # Sebatbeit /bʷe/; not used in Amharic.
    'ቨ': 'və',
    'ቩ': 'vu',
    'ቪ': 'vi',
    'ቫ': 'va',
    'ቬ': 've',
    'ቭ': 'vɨ',
    'ቮ': 'vo',
    'ቯ': 'vwa',
    'ተ': 'tə',
    'ቱ': 'tu',
    'ቲ': 'ti',
    'ታ': 'ta',
    'ቴ': 'te',
    'ት': 'tɨ',
    'ቶ': 'to',
    'ⶆ': 'to',  # Dizi, Me’en, Mursi, Suri /tɔ/; not used in Amharic.
    'ቷ': 'twa',
    'ቸ': 't͡ʃə',
    'ቹ': 't͡ʃu',
    'ቺ': 't͡ʃi',
    'ቻ': 't͡ʃa',
    'ቼ': 't͡ʃe',
    'ች': 't͡ʃɨ',
    'ቾ': 't͡ʃo',
    'ቿ': 't͡ʃwa',
    'ⶨ': 't͡ʃə',  # Unclear language; pronounced like ቸ in Amharic.
    'ⶩ': 't͡ʃu',
    'ⶪ': 't͡ʃi',
    'ⶫ': 't͡ʃa',
    'ⶬ': 't͡ʃe',
    'ⶭ': 't͡ʃɨ',
    'ⶮ': 't͡ʃo',
    'ኀ': 'ha',  # Pronounced like ሀ in Amharic.
    'ኁ': 'hu',
    'ኂ': 'hi',
    'ኃ': 'ha',
    'ኄ': 'he',
    'ኅ': 'hɨ',
    'ኆ': 'ho',
    'ኇ': 'ho',  # Dizi, Me’en, Mursi, Suri /ŋɔ/; not used in Amharic.
    'ኈ': 'hwə',
    'ኍ': 'hwu',
    'ኊ': 'hwi',
    'ኋ': 'hwa',
    'ኌ': 'hwe',
    'ነ': 'nə',
    'ኑ': 'nu',
    'ኒ': 'ni',
    'ና': 'na',
    'ኔ': 'ne',
    'ን': 'nɨ',
    'ኖ': 'no',
    'ⶈ': 'no',  # Dizi, Me’en, Mursi, Suri /nɔ/; not used in Amharic.
    'ኗ': 'nwa',
    'ኘ': 'ɲə',
    'ኙ': 'ɲu',
    'ኚ': 'ɲi',
    'ኛ': 'ɲa',
    'ኜ': 'ɲe',
    'ኝ': 'ɲɨ',
    'ኞ': 'ɲo',
    'ⶉ': 'ɲo',  # Dizi, Me’en, Mursi, Suri /ɲɔ/; not used in Amharic.
    'ኟ': 'ɲwa',
    'አ': 'ʔə',
    'ኡ': 'ʔu',
    'ኢ': 'ʔi',
    'ኣ': 'ʔa',
    'ኤ': 'ʔe',
    'እ': 'ʔɨ',
    'ኦ': 'ʔo',
    'ⶊ': 'ʔo',  # Dizi, Me’en, Mursi, Suri /ɲɔ/; not used in Amharic.
    'ከ': 'kə',
    'ኩ': 'ku',
    'ኪ': 'ki',
    'ካ': 'ka',
    'ኬ': 'ke',
    'ክ': 'kɨ',
    'ኮ': 'ko',
    'ኰ': 'kwə',
    'ኵ': 'kwu',
    'ኲ': 'kwi',
    'ኳ': 'kwa',
    'ኴ': 'kwe',
    'ⷈ': 'kə',  # Sebatbeit /kʲ/; pronounced as /k/ in Amharic.
    'ⷉ': 'ku',
    'ⷊ': 'ki',
    'ⷋ': 'ka',
    'ⷌ': 'ke',
    'ⷍ': 'kɨ',
    'ⷎ': 'ko',
    'ⷐ': 'kə',  # Sebatbeit /xʲə/; pronounced as /kə/ in Amharic.
    'ⷑ': 'ku',
    'ⷒ': 'ki',
    'ⷓ': 'ka',
    'ⷔ': 'ke',
    'ⷕ': 'kɨ',
    'ⷖ': 'ko',
    'ወ': 'wə',
    'ዉ': 'wu',
    'ዊ': 'wi',
    'ዋ': 'wa',
    'ዌ': 'we',
    'ው': 'wɨ',
    'ዎ': 'wo',
    'ዏ': 'wo',  # Dizi, Me’en, Mursi, Suri /wɔ/; not used in Amharic.
    'ዐ': 'ʕə',
    'ዑ': 'ʕu',
    'ዒ': 'ʕi',
    'ዓ': 'ʕa',
    'ዔ': 'ʕe',
    'ዕ': 'ʕɨ',
    'ዖ': 'ʕo',
    'ዘ': 'zə',
    'ዙ': 'zu',
    'ዚ': 'zi',
    'ዛ': 'za',
    'ዜ': 'ze',
    'ዝ': 'zɨ',
    'ዞ': 'zo',
    'ⶋ': 'zo',  # Dizi, Me’en, Mursi, Suri /zɔ/; not used in Amharic.
    'ዟ': 'zwa',
    'ዠ': 'ʒə',
    'ዡ': 'ʒu',
    'ዢ': 'ʒi',
    'ዣ': 'ʒa',
    'ዤ': 'ʒe',
    'ዥ': 'ʒɨ',
    'ዦ': 'ʒo',
    'ዧ': 'ʒwa',
    'ⶰ': 'ʒə',  # Unclear language; pronounced like ዠ in Amharic.
    'ⶱ': 'ʒu',
    'ⶲ': 'ʒi',
    'ⶳ': 'ʒa',
    'ⶴ': 'ʒe',
    'ⶵ': 'ʒɨ',
    'ⶶ': 'ʒo',
    'የ': 'jə',
    'ዩ': 'ju',
    'ዪ': 'ji',
    'ያ': 'ja',
    'ዬ': 'je',
    'ይ': 'jɨ',
    'ዮ': 'jo',
    'ዯ': 'jo',  # Dizi, Me’en, Mursi, Suri /zɔ/; not used in Amharic.
    'ደ': 'də',
    'ዱ': 'du',
    'ዲ': 'di',
    'ዳ': 'da',
    'ዴ': 'de',
    'ድ': 'dɨ',
    'ዶ': 'do',
    'ⶌ': 'do',  # Dizi, Me’en, Mursi, Suri /zɔ/; not used in Amharic.
    'ዷ': 'dwa',
    'ጀ': 'd͡ʒə',
    'ጁ': 'd͡ʒu',
    'ጂ': 'd͡ʒi',
    'ጃ': 'd͡ʒa',
    'ጄ': 'd͡ʒe',
    'ጅ': 'd͡ʒɨ',
    'ጆ': 'd͡ʒo',
    'ጇ': 'd͡ʒwa',
    'ገ': 'ɡə',
    'ጉ': 'ɡu',
    'ጊ': 'ɡi',
    'ጋ': 'ɡa',
    'ጌ': 'ɡe',
    'ግ': 'ɡɨ',
    'ጎ': 'ɡo',
    'ጐ': 'ɡwə',
    'ጕ': 'ɡwu',
    'ጒ': 'ɡwi',
    'ጓ': 'ɡwa',
    'ጔ': 'ɡwe',
    'ጘ': 'ŋə',  # Awngi, Blin, Qimant, Xamtanga /ŋ/.
    'ጙ': 'ŋu',
    'ጚ': 'ŋi',
    'ጛ': 'ŋa',
    'ጜ': 'ŋe',
    'ጝ': 'ŋɨ',
    'ጞ': 'ŋo',
    'ⶓ': 'ŋwə',
    'ⶖ': 'ŋwu',
    'ⶔ': 'ŋwi',
    'ጟ': 'ŋwa',
    'ⶕ': 'ŋwe',
    'ⷘ': 'ɡə',  # Sebatbeit /ɡj/; pronounced as /ɡ/ in Amharic.
    'ⷙ': 'ɡu',
    'ⷚ': 'ɡi',
    'ⷛ': 'ɡa',
    'ⷜ': 'ɡe',
    'ⷝ': 'ɡɨ',
    'ⷞ': 'ɡo',
    'ጠ': 'tʼə',
    'ጡ': 'tʼu',
    'ጢ': 'tʼi',
    'ጣ': 'tʼa',
    'ጤ': 'tʼe',
    'ጥ': 'tʼɨ',
    'ጦ': 'tʼo',
    'ጧ': 'tʼwa',
    'ጨ': 't͡ʃʼə',
    'ጩ': 't͡ʃʼu',
    'ጪ': 't͡ʃʼi',
    'ጫ': 't͡ʃʼa',
    'ጬ': 't͡ʃʼe',
    'ጭ': 't͡ʃʼɨ',
    'ጮ': 't͡ʃʼo',
    'ⶐ': 't͡ʃʼo',  # Dizi, Me’en, Mursi, Suri /t͡ʃʼɔ/; not used in Amharic.
    'ጯ': 't͡ʃʼwa',
    'ⶸ': 't͡ʃʼə',  # Bench /ʈ͡ʂʼ/; pronounced as /t͡ʃʼ/ in Amharic.
    'ⶹ': 't͡ʃʼu',
    'ⶺ': 't͡ʃʼi',
    'ⶻ': 't͡ʃʼa',
    'ⶼ': 't͡ʃʼe',
    'ⶽ': 't͡ʃʼɨ',
    'ⶾ': 't͡ʃʼo',
    'ጰ': 'pʼə',
    'ጱ': 'pʼu',
    'ጲ': 'pʼi',
    'ጳ': 'pʼa',
    'ጴ': 'pʼe',
    'ጵ': 'pʼɨ',
    'ጶ': 'pʼo',
    'ⶑ': 'pʼo',  # Dizi, Me’en, Mursi, Suri /pʼɔ/; not used in Amharic.
    'ጷ': 'pʼwa',


    'ጸ': 'sʼə',
    'ጹ': 'sʼu',
    'ጺ': 'sʼi',
    'ጻ': 'sʼa',
    'ጼ': 'sʼe',
    'ጽ': 'sʼɨ',
    'ጾ': 'sʼo',
    'ጿ': 'sʼwa',
    'ፀ': 'sʼə',  # Pronounced like ጸ in Amharic.
    'ፁ': 'sʼu',
    'ፂ': 'sʼi',
    'ፃ': 'sʼa',
    'ፄ': 'sʼe',
    'ፅ': 'sʼɨ',
    'ፆ': 'sʼo',
    'ፇ': 'sʼo',  # Dizi, Me’en, Mursi, Suri /sʼɔ/; not used in Amharic.
    'ፈ': 'fə',
    'ፉ': 'fu',
    'ፊ': 'fi',
    'ፋ': 'fa',
    'ፌ': 'fe',
    'ፍ': 'fɨ',
    'ፎ': 'fo',
    'ᎈ': 'fwə',  # Sebatbeit /fwə/; not used in Amharic.
    'ᎉ': 'fwu',  # Sebatbeit /fwu/; not used in Amharic.
    'ᎋ': 'fwi',  # Sebatbeit /fwi/; not used in Amharic.
    'ፏ': 'fwa',
    'ᎊ': 'fwe',  # Sebatbeit /fwe/; not used in Amharic.
    'ፚ': 'fja',  # Unclear language; transcribed as /fja/.
    'ፐ': 'pə',
    'ፑ': 'pu',
    'ፒ': 'pi',
    'ፓ': 'pa',
    'ፔ': 'pe',
    'ፕ': 'pɨ',
    'ፖ': 'po',
    'ⶒ': 'po',  # Dizi, Me’en, Mursi, Suri /pɔ/; not used in Amharic.
    'ᎌ': 'pwə',  # Sebatbeit /pwə/; not used in Amharic.
    'ᎍ': 'pwu',  # Sebatbeit /pwu/; not used in Amharic.
    'ᎏ': 'pwi',  # Sebatbeit /pwi/; not used in Amharic.
    'ፗ': 'pwa',
    'ᎎ': 'pwe',  # Sebatbeit /pwe/; not used in Amharic.
    'ኧ': 'ə'
}





def ipa_convert(text):
    ipa_convert=[]
    for i in text:
        ipa_word_convert=''
        for j in i:
            ipa_word_convert+=IPA.get(j,'')
        ipa_convert.append(ipa_word_convert)
        
    return ipa_convert


def ipa_convertor_alpahbet(text):
    ipa_converted_alphabet=[]
    for i in text:
        ipa_converted_alphabet.append(IPA.get(i,''))
    return ipa_converted_alphabet

